### ISSUE TITLE
Upgraded versions of elasticsearch and kibana

### ISSUE THREAD

**Issue by petiepooo** [capesstack/capes#89]
When running "yum update" after install, I see it offering to upgrade elasticsearch and kibana (to v6.4.3-1 when this issue was submitted).  Would this break integration with thehive and/or cortex?  If so, do we want to versionlock elasticsearch/kibana to keep them from automatically attempting to upgrade?

**Comment by peasead** [comment]
Yes, this will **definitely** break TheHive and Cortex because of the upstream dependencies.

That said, I can't replicate the request to upgrade Elasticsearch and Kibana. When I run `sudo yum update`, it offers to upgrade TheHive, but not Elasticsearch or Kibana. Did you install those manually?

Upgrading TheHive via `yum update` is totally fine.

**Comment by peasead** [comment]
Additionally, if you are having this issue because of your local build, you can run `echo "exclude=elasticsearch kibana" >> /etc/yum.conf`

**Comment by petiepooo** [comment]
I did have a more current version of those two installed previously, so I had an additional repository installed that's offering these newer versions.  It's my setup only, so it doesn't make sense to add the exclusion via script.  Thanks for the yum config tip.
